# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

first <- function(za, zb, stdv, nints, delta, bs) {
    .Call('_RTSA_first', PACKAGE = 'RTSA', za, zb, stdv, nints, delta, bs)
}

init_int <- function(wj, zj, delta, stdv) {
    .Call('_RTSA_init_int', PACKAGE = 'RTSA', wj, zj, delta, stdv)
}

trap <- function(f, n, h) {
    .Call('_RTSA_trap', PACKAGE = 'RTSA', f, n, h)
}

fcab <- function(last, nint, zam1, h, x, stdv, delta, k, bs) {
    .Call('_RTSA_fcab', PACKAGE = 'RTSA', last, nint, zam1, h, x, stdv, delta, k, bs)
}

other <- function(za, zb, k, stdv, last, nints, delta, bs) {
    .Call('_RTSA_other', PACKAGE = 'RTSA', za, zb, k, stdv, last, nints, delta, bs)
}

recur_int <- function(k, stdv, zj, last, zj_up, wj_up, delta, bs) {
    .Call('_RTSA_recur_int', PACKAGE = 'RTSA', k, stdv, zj, last, zj_up, wj_up, delta, bs)
}

qpos <- function(xq, last, nint, k, zam1, zbm1, stdv, bs, delta) {
    .Call('_RTSA_qpos', PACKAGE = 'RTSA', xq, last, nint, k, zam1, zbm1, stdv, bs, delta)
}

prob <- function(xq, last, zj, k, stdv, bs, delta) {
    .Call('_RTSA_prob', PACKAGE = 'RTSA', xq, last, zj, k, stdv, bs, delta)
}

